import Head from 'next/head'
import styles from '/styles/Home.module.css'

export default function ProductList() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next js </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <p className={styles.title}>
                        Product <span style={{ color: 'green' }}>one</span>
                    </p>
                    <p className={styles.title}>
                        Product <span style={{ color: 'orange' }}>Two</span>
                    </p>
                    <p className={styles.title}>
                        Product <span style={{ color: 'red' }}>Three</span>
                    </p>
                </div>
            </main>
        </div>
    )
}