import Head from 'next/head'
import styles from '/styles/Home.module.css';
import Link from 'next/link';

export default function ProductList({ productId = 120 }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next js </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href="/">
                    <a style={{ justifyContent: 'center' }} className={styles.aa} >Home</a>
                </Link>
                <div >
                    <p className={styles.title}>
                        <Link href="/product/1" >
                            <a> Product <span style={{ color: 'green' }}>one</span></a>
                        </Link>
                    </p>
                    <p className={styles.title}>
                        <Link href="/product/2" >
                            <a> Product <span style={{ color: 'orange' }}>Two</span></a>
                        </Link>
                    </p>
                    <p className={styles.title}>
                        <Link href="/product/3" replace >
                            <a> Product <span style={{ color: 'pink' }}>Three</span></a>
                        </Link>
                    </p>
                    <p className={styles.title}>
                        <Link href={`/product/${productId}`} >
                            <a> Product <span style={{ color: 'pink' }}>{productId}</span></a>
                        </Link>
                    </p>
                </div>
            </main>
        </div>
    )
}