import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '/styles/Home.module.css'
export default function product({ product }) {
    const router = useRouter()
    if (router.isFallback) {
        return <h1 style={{ color: 'red', position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)' }} >Loading...</h1>
    }

    return (
        <div>
            <Head>
                <title>Next js </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <p className={styles.title}>
                    <a>{product.title}</a>
                </p>
                <div style={{ width: '30%' }} >
                    <p>{product.id} : {product.description}</p>

                </div>
            </main>
        </div>
    )
}
export async function getStaticProps(context) {
    const { params } = context
    console.log(`regenerating product ${params.productId}`)
    const response = await fetch(`http://localhost:4000/products/${params.productId}`)
    const data = await response.json()

    if (!data.id) {
        return {
            notFound: true,
        }
    }

    console.log(`Generating page for /posts/${params.productId}`)
    return {
        props: {
            product: data
        },
        revalidate: 5
    }
}
export async function getStaticPaths() {
    return {
        paths: [{ params: { productId: '1' } }],
        fallback: true
    }
}