import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import styles from '/home/nauman/next/Next-framework/styles/Home.module.css'



export default function ProductList({ products }) {
    const [comments, setComments] = useState([])
    const [comment, setComment] = useState('')


    const fetchComments = async () => {
        const response = await fetch(`/api/comments`)
        const data = await response.json()
        setComments(data)
    }
    const submitComment = async () => {
        const response = await fetch('/api/comments', {
            method: 'POST',
            body: JSON.stringify({ comment }),
            headers: {
                'content-Type': 'application/json'
            },
        })
        const data = await response.json()
        console.log(data)
    }

    const deleteComment = async commentId => {
        const response = await fetch(`/api/comments/${commentId}`, { method: 'DELETE' })
        const data = await response.json()
        console.log(data)
        fetchComments()
    }

    return (
        <div>
            <Head>
                <title>Next js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p className={styles.title}>
                    <a>products !</a>
                </p>
                {products.map((product) => {
                    return (
                        <div key={product.id}>
                            <Link href={`products/${product.id}`} passHref >
                                <p>{product.id}  {product.title} <br /> price: {product.price}</p>
                            </Link>
                        </div>
                    )
                })}
                <input type="text"
                    value={comment}
                    onChange={(e) => setComment(e.target.value)}
                />
                <a style={{ justifyContent: 'center' }} className={styles.aa} onClick={submitComment} >New comment</a>
                <a style={{ justifyContent: 'center' }} className={styles.aa} onClick={fetchComments} >Comments</a>
                {
                    comments.map((comment => {
                        return (
                            <div key={comment.id}>
                                <p>{comment.id}  {comment.text} </p>
                                <a style={{ justifyContent: 'center' }} className={styles.aa} onClick={() => deleteComment(comment.id)} >Delete</a>
                            </div>
                        )
                    }))
                }
            </main>
        </div>
    )
}

export async function getStaticProps() {
    console.log('regenerating product list')
    const response = await fetch('http://localhost:4000/products')
    const data = await response.json()
    return {
        props: {
            products: data,
        },
        revalidate: 5,
    }
}