import Head from 'next/head';
import Link from 'next/link';
import styles from '/home/nauman/next/Next-framework/styles/Home.module.css'

export default function NewsArticaleList({ articles }) {
    return (
        <div>
            <Head>
                <title>Next js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p className={styles.title}>
                    <a>News</a>
                </p>
                {articles.map((article) => {
                    return (
                        <div key={article.id}  >
                            <p> <span style={{ color: 'red' }}>{article.title}</span> <br />   <span style={{ color: 'green' }}>
                                {article.category}</span> </p>
                            <div style={{ width: '30vw' }} > <p >{article.description}</p></div>
                            <hr />
                        </div>
                    )
                })}

            </main>
        </div>
    )
}

export async function getServerSideProps() {
    const response = await fetch('http://localhost:4000/news')
    const data = await response.json()
    return {
        props: {
            articles: data,
        },
    }
}