import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function EventList({ eventList }) {
    const [events, setEvents] = useState(eventList)
    const router = useRouter()
    const fetchSportsEvents = async () => {
        const response = await fetch('http://localhost:4000/events?category=sports')
        const data = await response.json()
        setEvents(data)
        router.push('/events?category=sports', undefined, { shallow: true })
    }
    return (
        <div>
            <Head>
                <title>Next js </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href="/">
                    <a style={{ justifyContent: 'center' }} className={styles.aa} >Home</a>
                </Link>
                <a style={{ justifyContent: 'center' }} className={styles.aa} onClick={fetchSportsEvents} >Sports event</a>
                <h1 className={styles.title}>
                    <a>Events</a>
                </h1>
                {
                    events.map((event => {
                        return (
                            <div key={event.id}>
                                <p>{event.title} {event.date} | {event.category} <br /> {event.description} </p>
                            </div>
                        )
                    }))
                }
            </main>
        </div>
    )
}

export async function getServerSideProps(context) {
    const { query } = context
    const { category } = query
    const queryString = category ? 'category=sports' : ''
    const response = await fetch(`http://localhost:4000/events?${queryString}`)
    const data = await response.json()

    return {
        props: {
            eventList: data
        },
    }
}