import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
export default function Home() {
    return (
        <div >
            <Head>
                <title>Next js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                    <h1 className={styles.title}>
                        Welcome to <a href="https://nextjs.org">Home Page !</a>
                    </h1>
                </div>
                <div className={styles.homebuttons}>
                    <Link href="/blog" >
                        <a className={styles.aa} >Blog</a>
                    </Link>
                    <Link href="/profile" >
                        <a className={styles.aa}>Profile</a>
                    </Link>
                    <Link href="/product" >
                        <a className={styles.aa}>Products</a>
                    </Link>
                </div>
            </main>
        </div>
    )
}