import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Profile() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next js </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href="/">
                    <a style={{ justifyContent: 'center' }} className={styles.aa} >Home</a>
                </Link>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">profile Page !</a>
                </h1>
            </main>
        </div>
    )
}