import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css'
import User from './components/user';

export default function UserList({ users }) {
    return (
        <div>
            <Head>
                <title>Next js </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href="/">
                    <a style={{ justifyContent: 'center' }} className={styles.aa} >Home</a>
                </Link>
                <h1 className={styles.title}>
                    <a>User list !</a>
                </h1>
                {users.map((user) => {
                    return (
                        <div key={user.id}>
                            <User user={user} />
                        </div>
                    )
                })}
            </main>
        </div>
    )
}
export async function getStaticProps() {
    const response = await fetch('https://jsonplaceholder.typicode.com/users')
    const data = await response.json()
    return {
        props: {
            users: data,
        },
    }
}