import Head from 'next/head'
import styles from '/home/nauman/next/Next-framework/styles/Home.module.css'

export default function User({ user }) {
    return (
        <div>
            <Head>
                <title>Next js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p>Name :<span style={{ color: 'red' }}>{user.name}</span> </p>
                <p>emai :<span style={{ color: 'gray' }}>{user.email}</span> </p>
            </main>
        </div>
    )
}